home_path: ${oc.env:home_path}
data_dir: ${environment.home_path}/STELLA_code/experiments/
resume: True
world_size: 1
rank: -1
ngpu: 4
workers: 40
multiprocessing_distributed: True
distributed: True
dist_backend: 'nccl'
dist_url: 'tcp://224.66.41.62:23456'
node: 'localhost'
port: 21995
seed: 0
gpu: ''
slurm: False
slurm_partition: abhinav,all
slurm_timeout: 360
evaluate: False
nodelist: ""
exclude_nodes: ""
