name: 'Cls_Er'
args:
  reg_weight: 0.1
  plastic_model_update_freq: 0.8
  plastic_model_alpha: 0.999
  stable_model_update_freq: 0.6
  stable_model_alpha: 0.999
  batch_size: ${optim.per_gpu_batchsize}
  mem_args:
    memory_size: 2000
