defaults:
  - data: ave_finetune
  - data_augm: ave_augm
  - backbone: cav
  - criterion: ave
  - optim: adam
  - train_algo: finetune
  - cl_algo: finetune
  - environment: default
  - hydra: default
  - logging: default
